Removed all LOG lines
krharsh17/barview-android pull request #18
Opened 2020-02-29 18:43 UTC by Medhavi-16

2020-02-29 20:07 UTC, krharsh17 requested changes

2020-02-29 20:07 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/Bar.java
> +
```suggestion
```
Remove extra empty lines

2020-02-29 20:07 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/BarView.java
> +
Same

2020-02-29 20:07 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/BarView.java
> +
Same

2020-02-29 20:25 UTC, krharsh17 commented
Also, please mention the issue that you've submitted a PR for, as in this case #18 This will help in automatically closing the issue when the PR is merged!

2020-03-01 04:33 UTC, Medhavi-16 commented
Okay sir

On Sun, 1 Mar 2020, 01:55 Kumar Harsh, <notifications@github.com> wrote:

> Also, please mention the issue that you've submitted a PR for, as in this
> case #18 <https://github.com/krharsh17/barview-android/pull/18> This will
> help in automatically closing the issue when the PR is merged!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/krharsh17/barview-android/pull/18?email_source=notifications&email_token=AKPSVQI4NYC34LJZ3G4QBOLRFFXNLA5CNFSM4K646DM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENMFFOA#issuecomment-592990904>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKPSVQMVUS4S3B5WVIHMTUTRFFXNLANCNFSM4K646DMQ>
> .
>

2020-03-02 03:30 UTC, krharsh17 approved these changes

2020-03-02 03:32 UTC, merged