Constants branch
krharsh17/barview-android pull request #19
Opened 2020-02-29 20:26 UTC by Sourish-Mukherjee

**Objective**: Replace all inline static occurrences of default values for variables with static variables.

**Approach** : 

- Created an Interface named **Constants**
- Implemented **Constants** interface in **BarView** and **BarGroup** Class
- Modified **BarGroup** class, where I replaced all colour constant values with String variable name from Interface
- Modified **BarView** class, where I replaced all colour constant values with String variable name from Interface.

@krharsh17

2020-02-29 20:33 UTC, krharsh17 requested changes
Good job on the task! Just make these changes and your work will be merged 😀

2020-02-29 20:33 UTC, krharsh17 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" project-jdk-name="1.8" project-jdk-type="JavaSDK">
This change is not needed

2020-02-29 20:33 UTC, krharsh17 commented on app/build.gradle
> +    implementation 'com.github.krharsh17:barview-android:1.0'
Removing this will solve your CI build error.

2020-02-29 20:33 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/Constants.java
> +    String charArray = "0123456789ABCDEF";
Please use `camelCasing` in naming all variables throughout the project. For more details, refer to [this](https://en.wikipedia.org/wiki/Camel_case).

2020-02-29 21:20 UTC, Sourish-Mukherjee commented
@krharsh17 Fixed The Issus, regarding project-jdk-name, my system always makes it 1.8 since I am using 1.8 JDK. Thus I forcefully edited it.

2020-03-01 07:08 UTC, krharsh17 approved these changes
Well done!

2020-03-01 07:09 UTC, merged