Round Bars Created by creating a new Method.
krharsh17/barview-android pull request #35
Opened 2020-03-02 05:31 UTC by Alaska18

All the Bars of the BarView are given a Corner Radius

2020-03-02 06:20 UTC, krharsh17 requested changes

2020-03-02 06:20 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/BarGroup.java
> +        gradientDrawable.setCornerRadius(20);
Instead of setting a constant radius value to the bars, make it a variable.

2020-03-02 06:20 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/BarGroup.java
> +    public GradientDrawable SetUpRoundBars(int Color)
`Color` is used for class name. Change it to `color`
```suggestion
    public GradientDrawable SetUpRoundBars(int color)
```

2020-03-02 06:20 UTC, krharsh17 commented on library/src/main/java/in/krharsh17/barview/BarGroup.java
> +        bar.setBackground(SetUpRoundBars(Color.parseColor(color)));
Function names should begin with a lowercase letter.
```suggestion
        bar.setBackground(setUpRoundBars(Color.parseColor(color)));
```

2020-03-02 06:21 UTC, krharsh17 commented
Also, go through the Code Quality report and make the said changes.

2020-03-02 09:18 UTC, krharsh17 commented
There's still a quality error. Fix that please, and while you're doing that, could you also add a public setter method in BarView.java that would allow users to dynamically set the radius of the rounded bars using the barView object?

2020-03-02 13:49 UTC, Alaska18 commented
I have created the method so that users can set the corner radius but
obviously it is working only when the "barview.setcornerradius" is written
before "barview.setData". Is this okay?

On Mon, 2 Mar 2020, 14:48 Kumar Harsh, <notifications@github.com> wrote:

> There's still a quality error. Fix that please, and while you're doing
> that, could you also add a public setter method in BarView.java that would
> allow users to dynamically set the radius of the rounded bars using the
> barView object?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/krharsh17/barview-android/pull/35?email_source=notifications&email_token=AM2M3GZRBYV43V5KKQ3ZEL3RFN2XZA5CNFSM4K7MZN52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENORDRY#issuecomment-593301959>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM2M3GZEXXYCE3PSMHVRGRLRFN2XZANCNFSM4K7MZN5Q>
> .
>

2020-03-02 15:09 UTC, krharsh17 commented
I think you'll need to define two methods here, one which is light and can be used before `setData()` has been called, and the other which involves repopulating the entire view hierarchy of the library, but can be used only after `setData()` has been called. Maybe you can use a third method which would be publically accessible, and this third method would check whether `setData()` has been called or not, ie. whether barview has been populated or not, and then it would call the required method to set the radius.

2020-03-03 03:23 UTC, Alaska18 commented
That issue is solved I made a method in BarGroup.java to set the corner
radius so that when set corner radius of Bar view is called it sets the
corner radius of both the java classes. Is this fine?

On Mon, 2 Mar 2020, 20:39 Kumar Harsh, <notifications@github.com> wrote:

> I think you'll need to define two methods here, one which is light and can
> be used before setData() has been called, and the other which involves
> repopulating the entire view hierarchy of the library, but can be used only
> after setData() has been called. Maybe you can use a third method which
> would be publically accessible, and this third method would check whether
> setData() has been called or not, ie. whether barview has been populated
> or not, and then it would call the required method to set the radius.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/krharsh17/barview-android/pull/35?email_source=notifications&email_token=AM2M3G5D4LXVIJ2CDEAPTJDRFPD3LA5CNFSM4K7MZN52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENPVDFY#issuecomment-593449367>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM2M3G4XZY76FAL4EDLNJPLRFPD3LANCNFSM4K7MZN5Q>
> .
>

2020-03-03 14:00 UTC, krharsh17 commented
I think it should work. It'll have to be tested though.

2020-03-08 15:10 UTC, krharsh17 approved these changes

2020-03-08 15:10 UTC, merged