add shadow to bar view
krharsh17/barview-android pull request #47
Opened 2020-03-07 18:07 UTC by rajkothari634

added shadow to bar view

2020-03-10 08:10 UTC, sidhuparas commented
Kindly remove unused imports as suggested in PR Quality Review and solve the conflicts.

2020-03-10 10:41 UTC, samagragupta reviewed
Resolve conflicts

2020-03-13 16:19 UTC, ShivangiSingh17 commented
@rajkothari634 solve the conflicting files and squash the commits once you are done resolving the errors.

2020-03-15 16:40 UTC, krharsh17 commented
@rajkothari634 what's the status on this?

2020-03-15 16:56 UTC, rajkothari634 commented
Improving the effect of shadow

On Sun, Mar 15, 2020, 22:10 Kumar Harsh <notifications@github.com> wrote:

> @rajkothari634 <https://github.com/rajkothari634> what's the status on
> this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/krharsh17/barview-android/pull/47#issuecomment-599234516>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAMMMEYQY27Z2Q7ZELLFU3RHUAIVANCNFSM4LDRYA5A>
> .
>

2020-03-17 18:05 UTC, ShivangiSingh17 requested changes

2020-03-17 18:05 UTC, ShivangiSingh17 commented on library/src/main/java/in/krharsh17/barview/BarGroup.java
> +        //initial.setBackgroundColor(Color.parseColor(color));
Are you trying to reflect it over the whole page activity?

2020-03-17 18:05 UTC, ShivangiSingh17 commented on library/src/main/java/in/krharsh17/barview/BarGroup.java
> +
Avoid adding unnecessary spaces.

2020-03-25 13:44 UTC, closed without merging